# vim:fileencoding=utf-8:foldmethod=marker

include ./kitty-themes/themes/tokyo-night-kitty.conf

font_family     GeistMono Nerd Font
font_size       13

disable_ligatures yes
enable_audio_bell no

shell zsh
shell_integration no-cursor

cursor_shape    beam
cursor_shape_unfocused beam

url_color #e8eaed
url_style curly

remember_window_size no
window_padding_width 15
cursor_blink_interval 0

background_opacity 0.50
confirm_os_window_close 0

sync_to_monitor no

# allow_remote_control yes


